"use client";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./index.scss";
import ReduxProvider from "./store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
